language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

addons:
  apt:
    packages:
      - fakeroot
      - binutils

services: docker

script:
  - cd $TRAVIS_PHP_VERSION
  - sh ../meta/package.sh $(cat php-package)
  - composer install
  - docker build -t xpcmd/test:$TRAVIS_PHP_VERSION .
  - docker run --rm xpcmd/test:$TRAVIS_PHP_VERSION -e '$this->assertTrue(true)'

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push xpcmd/test:$TRAVIS_PHP_VERSION
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then
      docker tag xpcmd/test:$TRAVIS_PHP_VERSION xpcmd/test:latest;
      docker push xpcmd/test:latest;
    fi